### ISSUE TITLE
feat: add duration to the footer social media icons

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#103]
onHover effect on three of those icons inside the footer (probably inside of hamburger menu, I can't remember) currently takes action in an instant. While other hover effects have `duration-300` with TailwindCSS configuration set. So all you need to do is simply add duration, and everything that goes with it (`transition` or `ease-in-out` if they are not already added).

**Comment by coder-abdo** [comment]
hi @anicmarko9 
can I handle this issue?

**Comment by anicmarko9** [comment]
Make sure you don't commit any kind of package-lock file. Also, before you make PR, run these three commads to make sure that everything is in order:
1. `npm run typecheck`
1. `npm run ci:lint`
1. `npm run format`
