### ISSUE TITLE
refactor: hover effect

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#108]
Specifically on the `Logo` component, but also make sure that links in footer don't **"jump"** up on hover. Remove jumping animation, and add something else. Maybe for the footer links leave it as an onHover -> change color to primary, but no jumping up. Logo can stay like it is, only reduce transparency by 30%, but if you have something else in mind, let me know.

**Comment by coder-abdo** [comment]
Hi @anicmarko9 
I can handle this.

**Comment by jakepears** [comment]
I would like to suggest a adding a custom ease to all the hover effects. 

'transition: transform cubic-bezier(0.465, 0.183, 0.153, 0.946)'
//Add to /styles/animation.css
Something like this should add an ease similiar to Power4 of gsap.
