### ISSUE TITLE
feat: extend offer to last longer

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#12]
Currently, offer ends in 6 days. Just refactor code to extend it to last for about at least 29 days.

**Comment by jmorofsky** [comment]
Hi, I'd like to work on this. Should the end time be hardcoded to be 29 days from today or would you like it to always be 29 days from the current date?

**Comment by anicmarko9** [comment]
Hard coded, in this issue you just have to change the month from 08 to 09, or something like that.

Feel free to make it as complex as you like, though.
