### ISSUE TITLE
refactor: navbar style

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#127]
It's bad. Make something user friendly. Me personally, I'd just give it background color, then change the styling of all navbar links, etc. But freestyle however you feel like it's the best approach.

Try using colors defined inside of `tailwind.config.js`. If you want to use any other color, define it first inside that file, than use it on navbar.

**Comment by seddboi** [comment]
I have adjusted the styling, please assign me to the issue :)

**Comment by anicmarko9** [comment]
Just don't push the `package-lock.json` file, please. Lately, everybody has been pushing it, I don't know why 😅
