### ISSUE TITLE
style: landing page not responsive

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#135]
Due to many recent contributions, some changes made the LandingPage unresponsive for smaller screens. It's unresponsive even on the bigger screens.

On the smaller screens, it should be column of:
1. title
1. counter
1. text
1. button

But instead of that, the counter background is overlapping everything.

On the wider screens, it should be somewhat like it currently is, but look at the margins. It's so empty on the bottom half of the screen. I mean, the whole app on 1920x1080 is terrible, but for now we should only reduce empty space of the landing page.

**Comment by abdullah-25** [comment]
can I take this?

**Comment by abdullah-25** [comment]
fixed it and created a pull request for review
