### ISSUE TITLE
style: responsive landing page

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#139]
Previous contributions lead to unresponsive landing page design. Here are the images:

## Image 1 (320px width)
![landing-1](https://github.com/anicmarko9/responsive-front/assets/73799942/a2378ecb-b73d-4b2d-918b-146992b76d9e)
- Container blur takes over the button

## Image 2 (1920px width)
![landing-2](https://github.com/anicmarko9/responsive-front/assets/73799942/5d05d5f7-509f-43a3-8838-4315d591fdd9)
- Unnecessary empty space on the bottom half of the screen

## Image 3 (Somewhere around 1200px width)
![landing-3](https://github.com/anicmarko9/responsive-front/assets/73799942/a00105ac-321a-4470-981b-a599011b32a9)
- Title too big
- No space between button and the second content below it

## Image 4 (Somewhere around 700px - 900px width)
![landing-4](https://github.com/anicmarko9/responsive-front/assets/73799942/c6c4ac53-5079-4b3a-b82d-aec2bb117dff)
- Container blur takes over everything

**Comment by Razthyae** [comment]
I can try to work on this, can you assign me?

**Comment by Razthyae** [comment]
#142 
Managed to fix most of the problems:  blurred overlapping container and too much empty space.
Not sure about "Image 3 (Somewhere around 1200px width) - title too big" though - is it still too big with justify-evenly prop?

**Comment by anicmarko9** [comment]
It's somewhat good on our 1500px laptops, but it's terrible everywhere else. I'll open another issue with images so you can see how it is. If you want to work on it, you don't need me to assign you, just open another PR and I'll review it.
