### ISSUE TITLE
feat: animate FAQ dropdown button

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#15]
Currently, FAQ button opens in an instant. Make sure it animates like the hamburger menu, for an example. When you click on hamburger menu, it takes one second to slide in the screen. I need something similar for FAQ button, when pressed on it should slowly expand towards bottom.

**Comment by anubhav1206** [comment]
where's the FAQ button?

**Comment by anicmarko9** [comment]
If you can't find it, try solving easier issue.
