### ISSUE TITLE
feat: add or fix hamburger menu animation on close

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#160]
- Make sure you can click outside of hamburger menu, on "dark" rectangle, which will close the hamburger menu (with animation).
- Make sure animation works when you click `X` button. Currently it closes instantly.
- Make sure Hamburger Menu icons are color of `primary` instead of `black`. If you can't change `text-primary`, or `bg-primary`, or `border-primary`, then import different icons which allow that.
- Make sure you modify animations inside of `tailwind.config.js`, not inside of `index.css`.

**Comment by Fernandojbf123** [comment]
Hello my friend. I'd like to do this.
