### ISSUE TITLE
refactor: adjust margin between button and cards inside of card container

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#17]
That yellow button under 4 cards that present stats about clients and reviews. There is an unnecessary gap between those two elements.

**Comment by kalil0321** [comment]
Can you provide a picture please?

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by anicmarko9** [comment]
Actually, this doesn't work for all screen widths. Try modifying file ./src/index.css and find what's causing this issue. I'm assuming it's this line of code, specifically with mb-4.

```tsc
.statCard {
    @apply mb-4 flex h-40 w-[47%] flex-col items-center justify-center space-y-3 rounded-3xl bg-customWhite px-2 text-center 
        sm:h-48 sm:w-[22%] sm:justify-around sm:space-y-0 sm:rounded-2xl sm:px-4 xl:h-60 xl:justify-center xl:space-y-8 
        xl:rounded- 3xl;
  }
```

**Comment by Maciejlys** [comment]
@anubhav1206 go ahead

**Comment by anubhav1206** [comment]
> @anubhav1206 go ahead

made the changes, kindly check.
