### ISSUE TITLE
style: swap colors of these two icons

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#193]
![image](https://github.com/anicmarko9/responsive-front/assets/73799942/fa8a56ea-baa6-42b7-82eb-f4ecc6293df9)

Message should be `primary` (if that is pink), and the Suitcase should be `secondary` (if that is light blue). Make sure you also adjust all the hover effects, and other effects accordingly.

**Comment by Fernandojbf123** [comment]
Hello my friend, I am going to work in this one.
