### ISSUE TITLE
style: yellow block

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#228]
Make yellow rectangle a straight rectangle, with a little bit of rounding on the edges. I'm assuming that it's going to be something like `rounded-lg` or `rounded-xl`. If you see something like `rounded-tl-xl`, remove it. The "tl" should represent top-left, but I want all sides the same, not just top left.

You only need to change some file inside of `src/styles/` directory.

**Comment by coder-abdo** [comment]
hey @anicmarko9 
can i handle it?
