### ISSUE TITLE
feat: add animation to FAQ content

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#232]
On click, make it open from the top to the bottom, with the text inside of the FAQ container slowly expanding. This should take about one second, and on the another click, collapse everything as it once was, also in one second.

**Comment by trba1810** [comment]
Hey,i've started to work on this issue and first part is finished with setTimeout of 1 second which after trying locally i think is too long,so let me know if you want maybe to do half second or something. Second part is animation i don't know if you want me to install something like Framer Motion?

**Comment by anicmarko9** [comment]
One second is okay. Install FM only if you really need it, but I think it can be done with some custom key frames and transitions. Do whatever you like.

**Comment by trba1810** [comment]
OK i will try to use either custom or with library already installed.
