### ISSUE TITLE
refactor: scroll bar

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#233]
I want scroll bar visible only above 1024px width. So, in tailwind, that's like `sm:` or you can reverse it with `max-sm:` or something similar.

The idea is to not show scroll bar to the mobile and tablet devices.

**Comment by davidkrupa** [comment]
@anicmarko9
You can assign this task to me. I will do this.

**Comment by trba1810** [comment]
Hey @davidkrupa i've already created pull request for this.
