### ISSUE TITLE
[Bug]: The Home section is not responsive.

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [anicmarko9/responsive-front#235]
Describe the bug
-The icon on the home page is colliding with text and also the navbar is colliding with offer section also.
To Reproduce
-Go to 'Home Page'
-set 14 inch laptop dimensions [Width: 12.20 inches / 30.99 cm. Height: 6.86 inches / 17.43 cm.].
-see the err
-The icon at home page is colliding with text and also offer section also collides.

Screenshot

<img width="957" alt="Screenshot 2023-09-14 124427" src="https://github.com/anicmarko9/responsive-front/assets/130988755/ebffed0a-f6df-4e4b-b87c-aff6268f3341">

Expected Behaviour
-The website should be responsive . 
-the icon and the navbar do not collide with text and the offer section

**Comment by anicmarko9** [comment]
The last commit removed `sticky` class. Since my internet is not working for 2 days, I can't really do anything to change and test website.

You can fix this issue by adding either `fixed` or `sticky` or something else.

Maybe just revert the latest commit, that should do it.

**Comment by Rohit-Sharmaa** [comment]
I will try to fix this issue and make a pr definitely

**Comment by Rohit-Sharmaa** [comment]
@anicmarko9 I have make changes into the code and now the website is working fine. I have test it locally.
Please review my code and merge it.
