### ISSUE TITLE
feat: add animation to FAQ component

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#243]
Classic dropdown animation.

**Comment by ivanosquis10** [comment]
Hi Marko, I want to work on the issue but when you refer to "Classic dropdown animation", exactly what style do you mean?

**Comment by ivanosquis10** [comment]
I made an animation that when clicked the opacity goes from 0 to 1, and makes the effect of appearing and disappearing.

**Comment by anicmarko9** [comment]
When you click on the button, the whole container expands with the text. When you click again, it collapses back.

**Comment by ivanosquis10** [comment]
yep, it's just that using the "details and summary" already has that "animation" by default, that's why I proposed an animation of appearing and disappearing smoothly, just an idea :)
