### ISSUE TITLE
feat: add /weight-loss-programs page

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#29]
Make a whole page however you like. Make sure it's not DRY, separate page into smaller JSX components, write clean code and format it with prettier & check for errors with eslint.

**Comment by Fernandojbf123** [comment]
Hello again my friend, I'ma take this one.
Do I have to install it and configure it or you already did it?

Regards

**Comment by anicmarko9** [comment]
Everything is already installed. You just need to clone repository, or if you already have cloned it, just type in your terminal:
`git checkout main` -> if you are not already on the main branch
`git pull origin main` -> if this creates conflicts somehow, clone whole repository.
