### ISSUE TITLE
refactor: any page

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#298]
Re-design any page. Try to follow some good UX/UI design online, doesn't matter which one. Any page except Landing Page.

**Comment by natTar235** [comment]
I would like to work on this task. Can you assign me please?

**Comment by natTar235** [comment]
I would like to work on this task. Can you assign me please?

**Comment by ivanosquis10** [comment]
Hiiiiii, can it be done by one person? If I want to refactor the subscription page, for example, could I do it?

**Comment by anicmarko9** [comment]
Sure, you can refactor anything you want.

**Comment by ivanosquis10** [comment]
This is my proposal:
![image](https://github.com/anicmarko9/responsive-front/assets/83567373/3326ac81-d2f2-4279-b638-3017b73336a9)

**Comment by anicmarko9** [comment]
Looks good, make sure it's responsive. Also, try to fill in content from top to bottom, meaning that footer shouldn't be visible when you click on that page, but when you scroll down, you should be able to see it.

If you are out of ideas on how to fit in the bottom half of the screen, you can use any illustration from `freepick` website, or any other image.

**Comment by ivanosquis10** [comment]
Okay, I'll see what I can do. And some sort of heading that says "Our plans" with a subtitle next to it?

**Comment by ivanosquis10** [comment]
Hi! I wll show you what I've been working on, let me know what you think. I've been sick so I haven't done anything :(

![image](https://github.com/anicmarko9/responsive-front/assets/83567373/1e921856-d31c-4d4a-9ad1-dfd25e5371e7)
![Imagen de WhatsApp 2023-10-02 a las 22 37 59_a2b3a8aa](https://github.com/anicmarko9/responsive-front/assets/83567373/e801d8f2-c7ea-4ccc-82af-af922dce772f)

**Comment by anicmarko9** [comment]
It looks nice, make PR.

Hope you get well soon!
