### ISSUE TITLE
style: change color to blue (secondary)

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#309]
![image](https://github.com/anicmarko9/responsive-front/assets/73799942/96e57363-0fa0-4ec1-9ed7-49363d8cba90)

Change color of icons in this side nav menu from pink to blue. I'm assuming the color name can be found in `tailwind.config.js` file. It's either `primary` or `secondary`, can't remember really.

Change icons, and all other effects (like on-hover) accordingly. Some of the icons might be `text-secondary`, but some might be `bg-secondary`, who knows...

**Comment by R894** [comment]
Hello, I'm interested in working on this issue
May I be assigned to it please?
