### ISSUE TITLE
feat: hover effect on header and footer links

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#40]
Currently, on hover shows Bold and Underline text, which messes up the flow of responsive design. Just remove this feature and add classic hover that changes only color, or maybe reduces opacity by 30%, or something every normal website has.

**Comment by whit3st** [comment]
Hi! I want to solve this problem but you can solve it by removing `hover:font-bold` class. Instead you can add `hover:scale:105` or `hover:text-gray-700`. Happy coding! Still, you can assign me to this as well if you do not want to tackle! :)

**Comment by anicmarko9** [comment]
Greetings. I post these issues so people can come and solve them, not me personally 😁

The idea is to let other people practice their coding skills, while I practice my code review skills. We both get something out of this. I will rarely fix issues myself, so if you have enough time go and fix this issue. Feel free to add whatever you like, you don't need me to "assign" you, make yourself comfortable.

Also, if you see something out of order, feel free to open an issue, and follow it up with the PR. Both of those count as a **contribution**.

Let me know if you have any other questions regarding OSC. Happy coding to you too 😀

**Comment by anicmarko9** [comment]
This issue was already resolved.
