### ISSUE TITLE
refactor: index.css -> tailwind.config.js

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#45]
Inside of `index.css` from 73rd line of code, and all the way below it should be changed. All of that code below line 73 is plain CSS. @anubhav1206 worked on this already, so you might take it from here.
- All classes like `nav-link`, `magic-text`, hover effects, and others should be in the format like:
```tsx
  .navLink {
    @apply 'add css attributes here, using TailwindCSS syntax'
  }
```
- All keyframes, and similar stuff should be inside of `tailwind.config.js`, like the rest of the animations, that follow TailwindCSS syntax.

**Comment by Vidhanvyrs** [comment]
hey @anicmarko9 Is the issue still open, if is then I am more than happy to be assigned for it

**Comment by anicmarko9** [comment]
I'm not really sure, but you can check it out and solve it, if it is still there.

**Comment by Vidhanvyrs** [comment]
i think it is already done so you can close this issue as the css is refactored to tailwindconfig file
