### ISSUE TITLE
refactor: change color on hover

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#50]
<img src="https://github.com/anicmarko9/responsive-front/assets/73799942/996b4dec-4694-4aea-b33c-4bf770eb1b49" alt="hover" width="400px" />

On hover color should match the color of the background below. These colors already exist in the `tailwind.config.js` file:
```js
colors: {
  primary: "#dd71c6",
  secondary: "#73c3f4",
  tertiary: "#ffd900",
  countdown: "#4D85B0",
  customWhite: "#f9f5f6",
},
```

Just change `bg-color` from current, to one of these colors to match it. Make sure you change all colors inside of that Card accordingly.

**Comment by michaelmuthomi** [comment]
Hey, am interested in taking on this issue if available.

**Comment by anicmarko9** [comment]
Go ahead, no need to ask 😁
