### ISSUE TITLE
refactor: reorganize file structure

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#56]
We need to change an already existing file structure of this project, into something like this below:
├── src/
│   ├── assets/
│   │   ├── images/
│   │   ├── fonts/
│   ├── components/
│   │   ├── Header.tsx
│   │   ├── Footer.tsx
│   │   └── ...
│   ├── pages/
│   │   ├── Home.tsx
│   │   ├── About.tsx
│   │   └── ...
│   ├── styles/
│   │   ├── tailwind.css
│   │   ├── global.css
│   ├── utils/
│   │   ├── api.ts
│   │   ├── helpers.ts
│   ├── App.tsx
│   ├── index.tsx
├── public/
│   ├── index.html
│   ├── favicon.ico
│   ├── manifest.json

Please don't delete any of the files, just re-organize them into an architecture like this above. After you are done, run:
1. `npm run typecheck`
1. `npm run ci:format`
1. `npm run ci:lint`

And if everything is okay, push it to remote branch and make PR.

**Comment by witherScript** [comment]
Hi! Can you please assign this to me? I'll use the above as a template.

**Comment by witherScript** [comment]
Thx Marko, do you want me to change config for moving assets from /public/ into /src/assets?

**Comment by anicmarko9** [comment]
Sure, do however you feel like is correct.

**Comment by witherScript** [comment]
pulled most recent - agreed w/ installing craco. i was fiddling with it today to try and alias some paths in WeightLossProgram, going to study your implementation of aliases for component paths. I ended up removing it on my fork earlier bc the complexity of config outweighed the scope of the issue. Stoked to see you have it working.

Split index.css file into multiple based on type, index.css is now ordered imports. 

/styles/ -> more modular: 
|── src/
│  ├── styles/
│     ├──  index.css
│     ├── animations.css
│     ├── icons.css
│     ├── textStyles.css
│     ├── containers.css
      ├── miscStyles.css

**Comment by anicmarko9** [comment]
I will leave this issue open since it needs more refactoring.
