### ISSUE TITLE
refactor: change on-hover effect of two containers

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#60]
Here is the current onHover version:
![image](https://github.com/anicmarko9/responsive-front/assets/73799942/8d686d59-e974-4715-a40c-bb92b21dc9d1)
The problem is that text can't be seen. Make background color on hover same as one of my already set colors from `tailwind.config.js` file, and make text color on hover white (including the `<hr />` tag).

By the way, title should be changed from `<p>` to `<h2>`, but that is not important now.

**Comment by abhip167** [comment]
Can i take it ?

**Comment by anicmarko9** [comment]
Yes, no need to ask 😁
