### ISSUE TITLE
feat: add hover effect on links

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#69]
![image](https://github.com/anicmarko9/responsive-front/assets/73799942/2cc9a4a3-4ab2-4d16-8fc2-11b7309d7701)

Please remove this **bold** + underline hover effect, and add something more human like. Probably on-hover will be `text-primary`, and also mini transition `transition duration-300 ease-in`, or something similar.

This hover effect needs to be fixed only on HamburgerMenu (mobile screen), and on Footer links.

**Comment by COLONEL-HERE** [comment]
I have successfully resolved the issue, and done the desired changes, Now how do I make PR ?

**Comment by anicmarko9** [comment]
Fork -> edit code -> Compare & pull

**Comment by COLONEL-HERE** [comment]
I have successfully make the PR, Kindly merge it.
