### ISSUE TITLE
style: lower down duration of some animations

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#79]
Currently, the duration for almost every animation is `duration-300` (300 miliseconds). This can be slow for some links on hover, etc.

For an example, hover links on footer should have a little bit shorter duration, maybe 50, or 100; instead of 300.

**Comment by SameerJS6** [comment]
Can I get assign for this Issue? So that I can work on it!

**Comment by SameerJS6** [comment]
- This Issue has been solved by #83 

You can close this Issue.

**Comment by SameerJS6** [comment]
- #83
