### ISSUE TITLE
style: add hover effect on Logo

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#81]
Keep in mind that Logo should be in three different places. But you still need to change only one file.

1. logo inside of header nav bar
1. logo in the footer
1. logo in the hamburger menu

I'm not sure if there is logo inside of hamburger menu, but if there is not, then simply add it. This is relatively easy.

Hover effect can be anything you like. It can even be only dropping opacity to 70%. Be creative, make something good looking.

**Comment by PrathameshhW** [comment]
I would like to work on this issue. Can you please assign to me ?
