### ISSUE TITLE
refactor: change name of countdownType.ts file

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#92]
`src/types/countdownType.ts` was created long time ago for only one export. Now that it has more exports, you should either:
1. rename file into something more globally acceptable (maybe ask ChatGPT for the good name that represents all exports)
1. make two more files, each should export one interface

**Comment by trba1810** [comment]
Hi i can solve this issue,do you want just to rename one file to something like Interfaces etc... or do you want for every component to have it's own interface file???

**Comment by anicmarko9** [comment]
Do whatever you feel like it's morally acceptable. I don't have any plans on how to structure them, but overall, you can make one big file with interfaces and export them individually, and if that file gets more than 100 lines of code, than you can make multiple smaller files, where you also export them. All those files should be inside of `/src/types/*` I suppose.
